terraform {
  required_providers {
    helm = {
      source = "hashicorp/helm"
      version = "2.11.0"
    }
  }
}

provider "helm" {
    kubernetes {
        config_path = "~/.kube/config" # Should be generated by Github Actions
    }
    
    registry {
      url = var.source_acr_server
      username = var.source_acr_client_id
      password = var.source_acr_client_secret
    }
}