name: Terraform Helm AKS Deployment

on:
  push:
    branches:
      - master # You can change this to the branch you want to trigger the workflow on

jobs:
  terraform-helm-aks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
# I get de Cluster Credentials with previous resource and group
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

# Execution of terraform
      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Configuration
        #run: terraform apply -auto-approve -var "azure_client_id=${{ secrets.source_acr_client_id }}" -var "azure_client_secret=${{ secrets.source_acr_client_secret }}" -var "acr_server_subscription=${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}"
        run: terraform apply -auto-approve 