name: Terraform Helm AKS Deployment

on:
  push:
    branches:
      - master # You can change this to the branch you want to trigger the workflow on

jobs:
  terraform-helm-aks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azcliversion: '2.0.80' # Update to the latest Azure CLI version

# I login into azure in order to use az
      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS_CLIENT_ID }} -p ${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }} 
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}
      
# I get de Cluster Credentials with previous resource and group
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

# Execution of terraform
      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Configuration
        #run: terraform apply -auto-approve -var "azure_client_id=${{ secrets.source_acr_client_id }}" -var "azure_client_secret=${{ secrets.source_acr_client_secret }}" -var "acr_server_subscription=${{ secrets.AZURE_CREDENTIALS_SUBSCRIPTION_ID }}"
        run: terraform apply -auto-approve 